// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQQNnLCyxUw1jW-LCm9shuMzf3M5HRWRc',
    appId: '1:488945839000:android:b2179c2db142a37d69d9ed',
    messagingSenderId: '488945839000',
    projectId: 'calendar-20251120-10269',
    storageBucket: 'calendar-20251120-10269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLNPir2XYSNdkbRKPaYr98U3QVWF6-v4',
    appId: '1:488945839000:ios:1326efab043dabaa69d9ed',
    messagingSenderId: '488945839000',
    projectId: 'calendar-20251120-10269',
    storageBucket: 'calendar-20251120-10269.firebasestorage.app',
    iosClientId: '488945839000-jo9bd9sj70vpldf4600vecs1d1v8k5ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.ch22SchedulerSocial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujK4rkFkgyrhvlq4f8EF_qCovxZYVoKg',
    appId: '1:488945839000:web:b145b1eeab5d31a769d9ed',
    messagingSenderId: '488945839000',
    projectId: 'calendar-20251120-10269',
    authDomain: 'calendar-20251120-10269.firebaseapp.com',
    storageBucket: 'calendar-20251120-10269.firebasestorage.app',
    measurementId: 'G-SP4TZC4JN3',
  );

}