// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs27l37MY8M75cpzzA79A9ewcAx1R8xGU',
    appId: '1:135625966838:android:8648bbcd043b895e1858d7',
    messagingSenderId: '135625966838',
    projectId: 'calendar-20251120-dd841',
    storageBucket: 'calendar-20251120-dd841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5_KxYeL4PSNsQGerfqBHZ829Y75-C9C8',
    appId: '1:135625966838:ios:8c2810e0323e15891858d7',
    messagingSenderId: '135625966838',
    projectId: 'calendar-20251120-dd841',
    storageBucket: 'calendar-20251120-dd841.firebasestorage.app',
    iosBundleId: 'com.example.ch20SchedulerFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8VbWpgyUj9jeMd2UMm45ygRBkbtcAoWQ',
    appId: '1:135625966838:web:eef32ff6a640e07c1858d7',
    messagingSenderId: '135625966838',
    projectId: 'calendar-20251120-dd841',
    authDomain: 'calendar-20251120-dd841.firebaseapp.com',
    storageBucket: 'calendar-20251120-dd841.firebasestorage.app',
    measurementId: 'G-QB1XZCXNKM',
  );

}